name: Test Workflow

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main
      - 'dev-*'
      - 'feature/**'

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"